apiVersion: v1
kind: Service
metadata:
  name: www-service
spec:
  type: LoadBalancer
  selector:
    app: www
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30001
      targetPort: 30000