apiVersion: v1
kind: Service
metadata:
  name: www-service
spec:
  type: NodePort
  selector:
    app: www
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 32100
      targetPort: www-port